# Generated by Django 5.2.3 on 2025-06-30 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactioncategory',
            old_name='name',
            new_name='label',
        ),
    ]
